### ISSUE TITLE
offset NumberFormatException

### ISSUE THREAD

**Issue by Denhai** [dvdme/forecastio-lib-java#12]
`java.lang.NumberFormatException: Invalid int: "10.5"` ...

Both `ForecastIO.offset` and `ForecastIO.offsetValue` have this issue.
Obviously, this only occurs in timezones with offsets that are not integers.

**Comment by intrications** [comment]
Any update on this fix?

**Comment by dvdme** [comment]
It is fixed and updated on maven.
If you use maven make sure to change from version 1.5.1 to 1.5.2 or use LATEST.
