### ISSUE TITLE
Version 1.5.3 won't compile in android studio project.

### ISSUE THREAD

**Issue by spatrickapps** [dvdme/forecastio-lib-java#19]
When i add 1.5.1 or 1.5.2 it works perfectly,but when i use 1.5.3 i get the following error.
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/eclipsesource/json/JsonArray$1;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

**Comment by dvdme** [comment]
JsonArray is a class from minimal-json, the json library forecastio-lib-java uses.
From that exception my guess is that some dex file got left behind and now there are to definitions of that class.
Is the jar file from minimal-json duplicated anywhere?

Could adding ````multiDexEnabled true```` to build.gradle defaultConfig help?

**Comment by spatrickapps** [comment]
i'm getting this now
```
:app:packageAllDebugClassesForMultiDex FAILED
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/eclipsesource/json/JsonArray$1.class
```

These are the libraries that i use
```
compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.diogobernardino:williamchart:2.1'
    compile 'com.github.dvdme:ForecastIOLib:1.5.3'
    compile 'com.android.support:percent:23.1.1'
```

**Comment by dvdme** [comment]
Can't you spot JsonArray class duplicated (Or minimal-json jar file) anywhere on Android Studio? 
Also, have you tried cleaning the build ( ```Build > Clean Project ``` ) ? 
Those errors really look like ```minimal-json``` was added twice when you changed versions.

**Comment by spatrickapps** [comment]
All the files in eclipsesource.json are duplicated.

List of files
```
JsonArray
JsonLiteral
JsonNumber
JsonObject
JsonParser
JsonString
JsonValue
JsonWriter
ParseException
```

**Comment by spatrickapps** [comment]
I looked in the folder and i cant find any duplicate files.

**Comment by dvdme** [comment]
If you use 1.5.2 does it still work ?
I think that forecastio-lib-java from gradle is asking for the latest minimal-json.
Because you added 1.5.2 first there should be two minimal-json, by reading the exception.
If you change to 1.5.2 and it doesn't work then it is probably it.
I will test it on android studio to see if I can compile with 1.5.3

**Comment by spatrickapps** [comment]
I use 1.5.2 and it works perfectly but if i change it to 1.5.3 i throws the error,even if i clean the project.

**Comment by dvdme** [comment]
Can you send me an example a android studio project with that issue?
Em 29/12/2015 9:27 da tarde, "Sean Patrick" <notifications@github.com>
escreveu:

**Comment by spatrickapps** [comment]
[Forecastioexample.zip](https://github.com/dvdme/forecastio-lib-java/files/74861/Forecastioexample.zip)

**Comment by dvdme** [comment]
I tested it and I got the same issue.
The problem is that ```minimal-json``` is duplicated. It is embedded in the ```forecastio-lib-java``` and in the ```minimal-json``` jar.
This is because I wrongly uploaded to maven the ```forecastio-lib-java``` jar with the ```minimal-json``` dependency in it.
I already re-uploaded the corrected jar and when it updated in maven central repositories 1.5.3 should compile ok.
And by the way, happy new year!

**Comment by spatrickapps** [comment]
How long will it take to update?

http://maven-repository.com/artifact/com.github.dvdme/ForecastIOLib/1.5.3
Last modified	2015-11-17 23:54:26 UTC

**Comment by dvdme** [comment]
Short answer, I don't know.
Long answer, it is already updated here [search.maven.org](http://search.maven.org/#search|ga|1|ForecastIOLib)
Meanwhile, I've claimed owership of the package in [bintray](https://bintray.com) (which is what android studio uses, I think) to see if I can force an updated or something like that.

**Comment by spatrickapps** [comment]
Its only working when i download the jar from [bintray](https://bintray.com/dvdme/maven/com.github.dvdme%3AForecastIOLib/1.5.3/view#files/com/github/dvdme/ForecastIOLib/1.5.3) other than that its still not working.

**Comment by dvdme** [comment]
Ok, so removing the duplicated dependency fixed it but the central
repositories don't like re-syncing the same version.
This weekend I will upload a version 1.5.4 with the problem fixed. This way
it should sync with all rpeositories.

2016-01-07 1:46 GMT+00:00 Sean Patrick <notifications@github.com>:

> Its only working when i download the jar from bintray
> <https://bintray.com/dvdme/maven/com.github.dvdme%3AForecastIOLib/1.5.3/view#files/com/github/dvdme/ForecastIOLib/1.5.3>
> other than that its still not working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dvdme/forecastio-lib-java/issues/19#issuecomment-169520137>
> .
>



-- 
*David Ervideira*

**Comment by dvdme** [comment]
Meanwhile I made some updates (merged a pull request to add proxy support) and I updated it on maven central to 1.5.5.
I build successfully the sample project on Android Studio with version 1.5.5.
Try it out and everything should work now.

**Comment by spatrickapps** [comment]
Everything working now, Thanks.

**Comment by dvdme** [comment]
Cool, thanks for the feedback.
