### ISSUE TITLE
Publish `1.5.5` to jcenter?

### ISSUE THREAD

**Issue by loisaidasam** [dvdme/forecastio-lib-java#26]
Hi, I was wondering if you could publish version `1.5.5` to jcenter?

http://jcenter.bintray.com/com/github/dvdme/ForecastIOLib/

It seems that `1.5.3` is the latest available one, but you mention in the README to `Avoid using 1.5.3 and 1.5.4`.

Thanks!

**Comment by dvdme** [comment]
Not 1.5.5 but the latest, 1.6.0 is now published in JCenter
