### ISSUE TITLE
Cannot access latest snapshot in maven repo

### ISSUE THREAD

**Issue by aviadmini** [dvdme/forecastio-lib-java#30]
Basically I'm trying to use LATEST and it fails. I suspect that it's due to maven 3.x removing compatibility with those.

Could you push another release?
(or explain how to solve the issue)

Also jitpack.io fails to compile latest commits: [jitpack log](https://jitpack.io/com/github/dvdme/Forecastio-lib-java/fcf57f8ffd/build.log) which is because of missing imports. Solved [here](https://github.com/aviadmini/forecastio-lib-java)

**Comment by dvdme** [comment]
Latest are pushed to maven central.
